title: "Stability of defection, optimisation of strategies and the limits of
memory in the Prisoner's Dilemma."

repository: 
  url: "https://github.com/trallard/Memory-size-in-the-prisoners-dilemma"
  path_to_book: "nbs"
